// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqqwBE7Z0Ih4_zmWW9WFS4YouzvINijuA',
    appId: '1:62191359724:web:74c74ba8cd3d486f49f7c9',
    messagingSenderId: '62191359724',
    projectId: 'kurban-app',
    authDomain: 'kurban-app.firebaseapp.com',
    storageBucket: 'kurban-app.appspot.com',
    measurementId: 'G-8NRHR0GWS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKa4nRu8fCMxqfTXbrc0YeaqCmIaNgNrI',
    appId: '1:62191359724:android:91f8f4d6f349e75949f7c9',
    messagingSenderId: '62191359724',
    projectId: 'kurban-app',
    storageBucket: 'kurban-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvHD3mpbIG4R4fHjtun6ta-nh3JDDTANo',
    appId: '1:62191359724:ios:498f96c95bcc5e9849f7c9',
    messagingSenderId: '62191359724',
    projectId: 'kurban-app',
    storageBucket: 'kurban-app.appspot.com',
    iosBundleId: 'com.example.kurbanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvHD3mpbIG4R4fHjtun6ta-nh3JDDTANo',
    appId: '1:62191359724:ios:498f96c95bcc5e9849f7c9',
    messagingSenderId: '62191359724',
    projectId: 'kurban-app',
    storageBucket: 'kurban-app.appspot.com',
    iosBundleId: 'com.example.kurbanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqqwBE7Z0Ih4_zmWW9WFS4YouzvINijuA',
    appId: '1:62191359724:web:899ff802fb8dcf4849f7c9',
    messagingSenderId: '62191359724',
    projectId: 'kurban-app',
    authDomain: 'kurban-app.firebaseapp.com',
    storageBucket: 'kurban-app.appspot.com',
    measurementId: 'G-Y80CL4XLZ8',
  );
}
